### PR TITLE
[NKS-1351] Support Debian templates

### PR DESCRIPTION
**Pull request by sverrirsig**
This change to the injection scripts for user cluster masters/nodes allows Debian based templates with cloud-init to be used instead of Ubuntu.

### CODE REVIEW

**Comment by ntfrnzn** [comment]
the ssh connections will need attention too, since they hardcode the _ubuntu_ user

**Comment by sverrirsig** [comment]
I have to work out a weird quirk on Monday, but this is the gist of it. (Easy right?!?!)

The only change required in Chandler is to reference a new template, in this case debian-cloudimg-template on the Icelandic HCI. Which is just the bootVM OVA turned into template.

**Comment by sverrirsig** [comment]
@ntfrnzn Funny thing is that cloud-init creates an Ubuntu user. So you can actually _ssh ubuntu@xx.xx_.

**Comment by ntfrnzn** [comment]
`ssh ubuntu@ ` on debian seems ... not right.

**Comment by ntfrnzn** [comment]
! this repo is a fork of kubernetes-sigs/cluster-api-provider-vsphere, so we should keep the master branch clean & identical to upstream.  PRs should merge to `netapp`

**Comment by sverrirsig** [comment]
@ntfrnzn This is working wonders now - also adjusted according to your comments

**Comment by ntfrnzn** [comment]
it would be nice if we could toggle these templates off of machine.spec.providerSpec.value.machineSpec.template but maybe it's alright to just go forward since this is a true fork of the code.

**Comment by sverrirsig** [comment]
@ntfrnzn Did you get around to testing this?

**Comment by ntfrnzn** [comment]
Not yet. Also, we need some additional checks on installation to make sure that the template that is named is actually present.

**Comment by sverrirsig** [comment]
You're talking about doing that on the Chandler side?

**Comment by ntfrnzn** [comment]
https://jira.ngage.netapp.com/browse/NKS-1464

**Pull request merged**
